// Admin pages - full system access
export { default as Dashboard } from './Dashboard'
export { default as Employees } from './Employees'
export { default as Attendance } from './Attendance'
export { default as TimeOff } from './TimeOff'
export { default as Payroll } from './Payroll'
export { default as Reports } from './Reports'
export { default as MyProfile } from './MyProfile'
export { default as Settings } from './Settings'
export { default as Sidebar } from './Sidebar'
